// Code generated by protoc-gen-go.
// source: forwardcommand.proto
// DO NOT EDIT!

/*
Package Pmd is a generated protocol buffer package.

It is generated from these files:
	forwardcommand.proto

It has these top-level messages:
	Forward
	UserJsMessageForwardUserPmd_CS
	WebSocketForwardUserPmd_C
	WebSocketForwardUserPmd_S
	BehaviorMessageForwardUserPmd_CS
*/
package Pmd

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Forward_Param int32

const (
	Forward_UserJsMessageForwardUserPmd_CS Forward_Param = 1
	// LoginLobbyReq							= 2;
	// LoginLobbyRes							= 3;
	Forward_WebSocketForwardUserPmd_C        Forward_Param = 4
	Forward_WebSocketForwardUserPmd_S        Forward_Param = 5
	Forward_BehaviorMessageForwardUserPmd_CS Forward_Param = 6
)

var Forward_Param_name = map[int32]string{
	1: "UserJsMessageForwardUserPmd_CS",
	4: "WebSocketForwardUserPmd_C",
	5: "WebSocketForwardUserPmd_S",
	6: "BehaviorMessageForwardUserPmd_CS",
}
var Forward_Param_value = map[string]int32{
	"UserJsMessageForwardUserPmd_CS":   1,
	"WebSocketForwardUserPmd_C":        4,
	"WebSocketForwardUserPmd_S":        5,
	"BehaviorMessageForwardUserPmd_CS": 6,
}

func (x Forward_Param) Enum() *Forward_Param {
	p := new(Forward_Param)
	*p = x
	return p
}
func (x Forward_Param) String() string {
	return proto.EnumName(Forward_Param_name, int32(x))
}
func (x *Forward_Param) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Forward_Param_value, data, "Forward_Param")
	if err != nil {
		return err
	}
	*x = Forward_Param(value)
	return nil
}

type BehaviorMessageForwardUserPmd_CS_Type int32

const (
	BehaviorMessageForwardUserPmd_CS_NormalText BehaviorMessageForwardUserPmd_CS_Type = 1
	BehaviorMessageForwardUserPmd_CS_UploadTree BehaviorMessageForwardUserPmd_CS_Type = 2
)

var BehaviorMessageForwardUserPmd_CS_Type_name = map[int32]string{
	1: "NormalText",
	2: "UploadTree",
}
var BehaviorMessageForwardUserPmd_CS_Type_value = map[string]int32{
	"NormalText": 1,
	"UploadTree": 2,
}

func (x BehaviorMessageForwardUserPmd_CS_Type) Enum() *BehaviorMessageForwardUserPmd_CS_Type {
	p := new(BehaviorMessageForwardUserPmd_CS_Type)
	*p = x
	return p
}
func (x BehaviorMessageForwardUserPmd_CS_Type) String() string {
	return proto.EnumName(BehaviorMessageForwardUserPmd_CS_Type_name, int32(x))
}
func (x *BehaviorMessageForwardUserPmd_CS_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BehaviorMessageForwardUserPmd_CS_Type_value, data, "BehaviorMessageForwardUserPmd_CS_Type")
	if err != nil {
		return err
	}
	*x = BehaviorMessageForwardUserPmd_CS_Type(value)
	return nil
}

type Forward struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Forward) Reset()         { *m = Forward{} }
func (m *Forward) String() string { return proto.CompactTextString(m) }
func (*Forward) ProtoMessage()    {}

// 长连接时玩家跟区服务器的通信是通过网关转发的,统一用这个消息互相传递
type UserJsMessageForwardUserPmd_CS struct {
	Msg              *string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
	Msgbytes         []byte  `protobuf:"bytes,2,opt,name=msgbytes" json:"msgbytes,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UserJsMessageForwardUserPmd_CS) Reset()         { *m = UserJsMessageForwardUserPmd_CS{} }
func (m *UserJsMessageForwardUserPmd_CS) String() string { return proto.CompactTextString(m) }
func (*UserJsMessageForwardUserPmd_CS) ProtoMessage()    {}

func (m *UserJsMessageForwardUserPmd_CS) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func (m *UserJsMessageForwardUserPmd_CS) GetMsgbytes() []byte {
	if m != nil {
		return m.Msgbytes
	}
	return nil
}

// HTTP请求切换到websocket链接
type WebSocketForwardUserPmd_C struct {
	Accountid        *uint64 `protobuf:"varint,1,req,name=accountid" json:"accountid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *WebSocketForwardUserPmd_C) Reset()         { *m = WebSocketForwardUserPmd_C{} }
func (m *WebSocketForwardUserPmd_C) String() string { return proto.CompactTextString(m) }
func (*WebSocketForwardUserPmd_C) ProtoMessage()    {}

func (m *WebSocketForwardUserPmd_C) GetAccountid() uint64 {
	if m != nil && m.Accountid != nil {
		return *m.Accountid
	}
	return 0
}

type WebSocketForwardUserPmd_S struct {
	Accountid        *uint64 `protobuf:"varint,2,req,name=accountid" json:"accountid,omitempty"`
	Jsongatewayurl   *string `protobuf:"bytes,4,req,name=jsongatewayurl" json:"jsongatewayurl,omitempty"`
	Tokenid          *uint64 `protobuf:"varint,5,req,name=tokenid" json:"tokenid,omitempty"`
	Logintempid      *uint64 `protobuf:"varint,6,req,name=logintempid" json:"logintempid,omitempty"`
	Gatewayurl       *string `protobuf:"bytes,7,req,name=gatewayurl" json:"gatewayurl,omitempty"`
	Gatewayurltcp    *string `protobuf:"bytes,8,req,name=gatewayurltcp" json:"gatewayurltcp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *WebSocketForwardUserPmd_S) Reset()         { *m = WebSocketForwardUserPmd_S{} }
func (m *WebSocketForwardUserPmd_S) String() string { return proto.CompactTextString(m) }
func (*WebSocketForwardUserPmd_S) ProtoMessage()    {}

func (m *WebSocketForwardUserPmd_S) GetAccountid() uint64 {
	if m != nil && m.Accountid != nil {
		return *m.Accountid
	}
	return 0
}

func (m *WebSocketForwardUserPmd_S) GetJsongatewayurl() string {
	if m != nil && m.Jsongatewayurl != nil {
		return *m.Jsongatewayurl
	}
	return ""
}

func (m *WebSocketForwardUserPmd_S) GetTokenid() uint64 {
	if m != nil && m.Tokenid != nil {
		return *m.Tokenid
	}
	return 0
}

func (m *WebSocketForwardUserPmd_S) GetLogintempid() uint64 {
	if m != nil && m.Logintempid != nil {
		return *m.Logintempid
	}
	return 0
}

func (m *WebSocketForwardUserPmd_S) GetGatewayurl() string {
	if m != nil && m.Gatewayurl != nil {
		return *m.Gatewayurl
	}
	return ""
}

func (m *WebSocketForwardUserPmd_S) GetGatewayurltcp() string {
	if m != nil && m.Gatewayurltcp != nil {
		return *m.Gatewayurltcp
	}
	return ""
}

// 长连接时玩家跟区服务器的通信是通过网关转发的,统一用这个消息互相传递
type BehaviorMessageForwardUserPmd_CS struct {
	Msg              []string                               `protobuf:"bytes,1,rep,name=msg" json:"msg,omitempty"`
	Type             *BehaviorMessageForwardUserPmd_CS_Type `protobuf:"varint,2,opt,name=type,enum=Pmd.BehaviorMessageForwardUserPmd_CS_Type,def=1" json:"type,omitempty"`
	XXX_unrecognized []byte                                 `json:"-"`
}

func (m *BehaviorMessageForwardUserPmd_CS) Reset()         { *m = BehaviorMessageForwardUserPmd_CS{} }
func (m *BehaviorMessageForwardUserPmd_CS) String() string { return proto.CompactTextString(m) }
func (*BehaviorMessageForwardUserPmd_CS) ProtoMessage()    {}

const Default_BehaviorMessageForwardUserPmd_CS_Type BehaviorMessageForwardUserPmd_CS_Type = BehaviorMessageForwardUserPmd_CS_NormalText

func (m *BehaviorMessageForwardUserPmd_CS) GetMsg() []string {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *BehaviorMessageForwardUserPmd_CS) GetType() BehaviorMessageForwardUserPmd_CS_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Default_BehaviorMessageForwardUserPmd_CS_Type
}

func init() {
	proto.RegisterEnum("Pmd.Forward_Param", Forward_Param_name, Forward_Param_value)
	proto.RegisterEnum("Pmd.BehaviorMessageForwardUserPmd_CS_Type", BehaviorMessageForwardUserPmd_CS_Type_name, BehaviorMessageForwardUserPmd_CS_Type_value)
}

var Forward_Param_instance = map[string]interface{} {
	"UserJsMessageForwardUserPmd_CS": UserJsMessageForwardUserPmd_CS{},
	"WebSocketForwardUserPmd_C": WebSocketForwardUserPmd_C{},
	"WebSocketForwardUserPmd_S": WebSocketForwardUserPmd_S{},
	"BehaviorMessageForwardUserPmd_CS": BehaviorMessageForwardUserPmd_CS{},
}
